invoices/urls.py
from django.urls import path
from . import views

app_name = "invoices"

urlpatterns = [
    path('<pk>/', views.process_invoice_payment, name='pay-now'),
]

saleads/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'saleads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('user-accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('pricing-plans/', include('pricing_plans.urls', namespace='pricing_plans')),
    path('leads-and-tenders/', include('leads_and_tenders.urls', namespace='leads_and_tenders')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
    path('contact-us/', include('contact_us.urls', namespace='contact_us')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('service-provider/', include('service_provider.urls', namespace='service_provider')),
    path('invoices/', include('invoices.urls', namespace='invoices')),
]

invoices/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from decimal import *


class Invoice(models.Model):
    sp = models.ForeignKey('service_provider.ServiceProvider', related_name='sp_invoices', on_delete=models.CASCADE, blank=False)
    invoice_num = models.CharField(max_length=12, blank=False, unique=True)
    invoice_date = models.DateTimeField(default=timezone.now, blank=False)
    vat_percentage = models.IntegerField(default=15, blank=True)
    plan = models.ForeignKey('service_provider.PlanSubscription', blank=True, on_delete=models.CASCADE, null=True)
    paid = models.BooleanField(default=False, blank=False)
    notes = models.CharField(max_length=500, blank=True, null=True)

    def total(self):
        tot = Decimal(0.00).quantize(Decimal('0.00'))
        tot = Decimal(tot + self.plan.price * self.plan.duration).quantize(Decimal('0.00'))
        return tot

    def due_date(self):
        return self.invoice_date + timedelta(days=7)

    class Meta:
        verbose_name_plural = ('Invoices')

invoices/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
import requests
from .models import Invoice
from django.conf import settings
from urllib.parse import urlencode, quote_plus
import hashlib
from requests.exceptions import RequestException



@csrf_exempt
def process_invoice_payment(request, pk):
    # retrieve invoice in question.
    invoice = Invoice.objects.get(pk=pk)

    # Use payment gateway credentials securely on the server-side

    payfast_data = {
        'merchant_id': settings.MERCHANT_ID,
        'merchant_key': settings.MERCHANT_KEY,
        'return_url': 'https://tenderpros.herokuapp.com/user_accounts/payment_success/',
        'cancel_url': 'https://tenderpros.herokuapp.com/user_accounts/payment_cancelled/',
        'name_first': invoice.sp.user.first_name,
        'name_last': invoice.sp.user.last_name,
        'email_address': invoice.sp.user.email,
        'cell_number': invoice.sp.user.contactNumber,
        'm_payment_id': invoice.invoice_num,
        'amount': invoice.plan.plan.price,
        'item_name': invoice.plan.plan.name,
        'email_confirmation': '1',
        'confirmation_address': 'ayatech.co@gmail.com'
    }

    signature = ''
        # for key, value in payfast_data.items():
        #     signature += '{}={}&'.format(str(key), str(urllib.parse.urlencode(value)))

    signature = urlencode(payfast_data, quote_via=quote_plus)

    signature = hashlib.md5(signature.encode()).hexdigest()

    payfast_data.update({'signature': signature})

    try:
        # Process payment using payment gateway API
        # Replace this with your payment gateway API integration code
        response = requests.post(
            'https://www.payfast.co.za/eng/process',
            data = payfast_data
        )

        # Check if the request was successful (status code 2xx)
        response.raise_for_status()

        # Try to decode the JSON response
        result = response.json()

        # Handle the payment response
        if result.get('success'):
            return HttpResponseRedirect('')
        else:
            return JsonResponse({'message': 'Payment failed'})

    except RequestException as e:
        return JsonResponse({'message': f'Error processing payment: {str(e)}'}, status=500)

    

invoices/templates/invoice_code.html
{% load static %}

<div class="invoice">

    {% if global_invoice.paid == False %}

    <div style="text-align: center">
        <a href="{% url 'invoices:pay-now' pk=global_invoice.pk %}" class="btn btn-success btn-lg">Pay Now</a>
    </div>

    {% else %}

    <div style="text-align: center;">
        <h1><span class="text-success">PAID</span></h1>
    </div>

    {% endif %}


    <div class="invoice_outer_container p-4" style="text-align: center;" style="margin: 20px auto; border: 2px solid black;">
        <div style="text-align: center;"><h1>Invoice</h1></div>
        <hr>
        <div style="width: 50%; float: left; font-family: Arial, Helvetica, sans-serif; font-size: 0.75em;">

            <table style="text-align: left;">
                <tr>
                    
                    <td>
                        <table>
                            <tr>
                                <td colspan="2" style="font-size: 1.5em;"><strong>Ayatech (PTY) LTD T/A TenderPros</strong></td>
                            </tr>
                            <tr>
                                <td>Reg No.</td>
                                <td>2017/417565/07</td>
                            </tr>
                            <tr>
                                <td>VAT:</td>
                                <td>N/A</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>ayatech.co@gmail.com</td>
                            </tr>
                            <tr>
                                <td>Website:</td>
                                <td>https://www.tenderpros.co.za</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>

        </div>
        <div class="clear"></div>

        <div style="width: 50%; float: right; font-family: Arial, Helvetica, sans-serif;">
            <table style="text-align: left;">
                <tr>
                    <td>Date:</td>
                    <td>{{ global_invoice.invoice_date|date:"d M Y" }}</td>
                </tr>
                <tr>
                    <td>Invoice#:</td>
                    <td>{{ global_invoice.invoice_num }}</td>
                </tr>
            </table>

        </div>

        <div class="clear"></div>

        <br>
        
        <br>

        <div style="text-align: left;">
            <table>
                <thead>
                <th scope="col" width="35%"></th>
                <th scope="col" width="65%"></th>
                </thead>
                <tr>
                    <td colspan="2" style="font-size: 1.2em;"><strong>BILL TO:</strong></td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td><strong>{{ global_invoice.sp.name }}</strong></td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td>{{ global_invoice.sp.address }}</td>
                </tr>
                <tr>
                    <td>Contact Person:</td>
                    <td>{{ global_invoice.sp.user.get_full_name }}</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{ global_invoice.sp.user.email }}</td>
                </tr>
                <tr>
                    <td>Contact number:</td>
                    <td>{{ global_invoice.sp.contact_num}}</td>
                </tr>
            </table>
        </div>

        <br>

        <div style="height: 300px; border: 1px dashed black;">

            <table class="table table-borderless">
                <thead style="background: black; color: white;">
                <tr>
                    <th scope="col" width="55%">
                        DESCRIPTION
                    </th>
                    <th scope="col" width="5%">
                        QTY
                    </th>
                    <th scope="col" width="20%">
                        UNIT PRICE
                    </th>
                    <th scope="col" width="20%">
                        LINE TOTAL
                    </th>
                </tr>
                </thead>


                <tr>
                    <td>
                        <strong>{{ global_invoice.plan.plan.name }}</strong> <span>plan @ x12 Months</span>
                    </td>
                    <td>1</td>
                    <td>
                        {{ global_invoice.plan.plan.price }}
                    
                    </td>
                    <td>
                        {{ global_invoice.plan.plan.price }}

                    </td>
                   
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td><strong>SUBTOTAL</strong></td>
                    <td>
                        {{ global_invoice.plan.plan.price }}
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td><strong>VAT @ 15%</strong></td>
                    <td>
                        N/A
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td><strong>TOTAL</strong></td>
                    <td>
                        {{ global_invoice.plan.plan.price }}
                    </td>
                </tr>


            </table>

        </div>

        <br>

        <div id="banking_details" style="text-align: left;" style="font-size: .8em;">
            <h6 style="text-align: left;"><strong>TenderPros banking details</strong></h6>
            <table>
                <tr>
                    <td>Account holder:</td>
                    <td>Ayatech (PTY) LTD</td>
                </tr>
                <tr>
                    <td>Bank:</td>
                    <td>Capitec Bank</td>
                </tr>
                <tr>
                    <td>Account number:</td>
                    <td>1204144123</td>
                </tr>
                <tr>
                    <td>Branch Code:</td>
                    <td>470010</td>
                </tr>
                <tr>
                    <td>Ref:</td>
                    <td>{{global_invoice.plan.pymnt_ref}}</td>
                </tr>
            </table>
        </div>


        <div style="width: 40%; float: right;">
            <h6 style="text-align: left;"><strong><i>Notes:</i></strong></h6>
            <div class="p-2" style="text-align: left;" style="border: 1px solid black; height: 100px;">
                <p><i>The payment is due within 7 days of this invoice.</i></p>
            </div>
        </div>

        <div class="clear"></div>

        <br>

        <div style="background: grey; color: white;"><h3><i>THANK YOU FOR YOUR BUSINESS</i></h3></div>

    </div>


</div>