saleads/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'saleads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('user-accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('pricing-plans/', include('pricing_plans.urls', namespace='pricing_plans')),
    path('leads-and-tenders/', include('leads_and_tenders.urls', namespace='leads_and_tenders')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
    path('contact-us/', include('contact_us.urls', namespace='contact_us')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('service-provider/', include('service_provider.urls', namespace='service_provider')),
    path('invoices/', include('invoices.urls', namespace='invoices')),
]

user_accounts/urls.py
from django.urls import re_path, path, include

from django.contrib.auth import views as auth_views
from . import views 

# from tender_details.views import tenders_list_view, send_email_view
# from contact_us.views import contact_us_view, email_success_view
# from articleApp.views import article_view, article_list_view
# from tenderwiz.views import privacy_policy_view, termsAndConditions_view

app_name = "user_accounts"

urlpatterns = [
    path('auth/', views.auth_view, name='auth'),
    path('login/', auth_views.LoginView.as_view(template_name="authentication/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('logout_success/', views.logout_success_view, name='logout_success'),
    # re_path(r'^dashboard/', include('dashboard.urls')),
    path('register/<int:pk>/', views.Register.as_view(), name='register'),
    # re_path(r'^tenders/$', tenders_list_view, name='dashboard_tenders'),
    # re_path(r'^articles/$', article_list_view, name='dashboard_article_list'),
    # re_path(r'^article/(?P<article_pk>\d+)/$', article_view, name='article'),
    # re_path(r'^profile/$', profile_view, name='user_profile'),
    # re_path(r'^contact_us/$', contact_us_view, name='dashboard_contact_us'),
    # re_path(r'^billing/$', billing_view, name='billing'),
    # re_path(r'^invoice/(?P<inv_id>\d+)/$', Invoice_view, name='invoice'),
    path('registration_success/', views.registration_success_view, name='registration-success'),
    # re_path(r'^companyProfileEdit/(?P<pk>\d+)/$', UpdateCompanyProfile, name='company_profile_edit'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name="authentication/password_change.html"), name='password_change'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='authentication/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),
    path('find-keywords/', views.find_keywords, name="find-keywords")
    # re_path(r'^auto_complete_search/$', autocomplete_search_view, name='autocomplete_search'),
    # re_path(r'^send_email/$', send_email_view, name='sendEmail'),
    # re_path(r'^payment_success/$', Payment_Success_View, name='payment_success'),
    # re_path(r'^payment_cancelled/$', Payment_Cancelled_View, name='payment_cancelled'),
    # re_path(r'^termsAndConditions/$', termsAndConditions_view, name='dash_ts_and_cs'),
    # re_path(r'^privacy_policy/$', privacy_policy_view, name='dash_privacy_policy'),
    ]

user_accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, username, contactNumber, password=None, **extra_fields):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            username=username,
            contactNumber=contactNumber,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, contactNumber, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            password=password,
            contactNumber=contactNumber,
        )

        user.set_password(password)

        user.is_staff = True
        user.active = True
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)
        return user

  

# this is a custom user model.
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=200, blank=False, unique=True, null=True)
    saleads_id = models.CharField(max_length=20, unique=True, blank=False, null=True)
    contactNumber = models.CharField(max_length=20, blank=True, null=True)
    terms = models.BooleanField(blank=False, null=True)

    objects = CustomUserManager()

    # USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['contactNumber']

    class Meta:
        ordering = ['first_name']
        verbose_name_plural = ('Users')

    def __str__(self):
        return self.username

user_accounts/views.py
# from .utils import render_to_pdf

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.contrib import auth
from django.template.context_processors import csrf
from .forms import (
    CustomUserForm,
    PayFast_Form,                   
)

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.core import serializers
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse
import json
from urllib.parse import urlencode, quote_plus
import hashlib
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View, ContextMixin
from formtools.wizard.views import SessionWizardView
from formtools import wizard

from formtools.preview import FormPreview
from user_accounts.forms import CustomUserForm
from service_provider import forms as sp_forms
from service_provider.models import ServiceProvider, PlanSubscription
from leads_and_tenders.models import Keywords, Province, Category
from pricing_plans.models import PricingPlan
import random
import string
from invoices.models import Invoice

# this function generates an invoice number
def generate_invoice_number():
    # Get the last invoice number from the database
    last_invoice = Invoice.objects.order_by('-invoice_num').first()

    if last_invoice:
        new_invoice_number = last_invoice.invoice_num + 1
    else:
        # If no previous invoices, start with the initial invoice number
        new_invoice_number = 1000000

    return new_invoice_number

def generate_random_string():
    # Generate 4 random capital letters
    letters = ''.join(random.choice(string.ascii_uppercase) for _ in range(4))

    # Generate 4 random digits
    digits = ''.join(random.choice(string.digits) for _ in range(4))

    # Combine the letters and digits
    random_string = letters + digits

    # Shuffle the characters to make the order random
    random_string_list = list(random_string)
    random.shuffle(random_string_list)
    shuffled_string = ''.join(random_string_list)

    return shuffled_string


def logout_success_view(request):
    return render(request, 'user_accounts/logout_success.html')


def auth_view(request):
    username = request.POST.get('email', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect(reverse('dashboard:dashboard'))
    else:
        messages.warning(request, "Sorry, that's not a valid username and password")
        return HttpResponseRedirect(reverse('user_accounts:login'))
    

# handles user registrations.
FORMS = [
    ("0", CustomUserForm),
    ("1", sp_forms.SP_Form1),
    ("2", sp_forms.SP_Form2),
    ("3", PayFast_Form),
]

TEMPLATES = {
    '0': "registration/form1.html",
    '1': "registration/form2.html",
    '2': "registration/form3.html",
}

# handles  the purchasing of Third-Party Insurance.
class Register(SessionWizardView):
    form_list = [CustomUserForm, sp_forms.SP_Form1, sp_forms.SP_Form2]
    success_pg = "order-summary"

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]
    
    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        context['chosen_plan'] = PricingPlan.objects.get(pk=self.kwargs['pk'])              
        return context
    
    def done(self, form_list, form_dict, **kwargs):
        user_form = form_dict['0']
        user = user_form.save(commit=False)
        user.username = user.email
        user.save()

        # here we create the service provider profile.
        sp_type = form_dict['2'].cleaned_data['sp_type']
        trading_name = form_dict['1'].cleaned_data['trading_name']
        regnum = form_dict['1'].cleaned_data['regnum']
        address = form_dict['1'].cleaned_data['address']
        contact_num = form_dict['1'].cleaned_data['contact_num']
        provinces = form_dict['2'].cleaned_data['provinces']
        business_categories = form_dict['2'].cleaned_data['business_categories']
        business_keywords = form_dict['2'].cleaned_data['business_keywords']
        
        sp = ServiceProvider.objects.create(
            user=user,
            sp_type=int(sp_type),
            name=trading_name,
            reg_num=regnum,
            address=address,
            contact_num=contact_num
        )
        sp.contact_persons.add(user)
        # here we add the provinces to the sp's ManyToManyField of provinces
        for province in provinces:
            sp.provinces.add(province)
        
        for category in business_categories:
            sp.business_categories.add(category)

        biz_keyword = business_keywords.strip("[]").split(",")

        for keyword in biz_keyword:
            kw = keyword.strip('""').strip().strip("''")
            try:
                sp.business_keywords.add(Keywords.objects.get(pk=int(kw)))
            except Keywords.DoesNotExist:
                pass

        context = self.get_context_data(form=form_list[2])

        plan_subscription = PlanSubscription.objects.create(
            sp=sp, 
            plan=context['chosen_plan'], 
            status=4,
            pymnt_ref=generate_random_string()
        )
        
        invoice = Invoice.objects.create(
            sp=sp,
            invoice_num=generate_invoice_number(),
            plan=plan_subscription
        )

        return render(self.request, 'registration/registration_success.html', {
            'user': user,
            'sp': sp,
            'subscription': plan_subscription,
            'invoice': invoice
        })


# this view processing a payment through a PayFast gateway.
def process_payment(request):
    if request.method == 'POST':
        invoice = Invoice.objects.get(pk=inv_num)
        compProfile = invoice.company
        userObj = compProfile.user

        ourDetails = OurDetails.objects.get(compRegNum='2017/417565/07')

        amount = None

        if compProfile.contractDuration == 6:
            amount = compProfile.package.sixMonthPrice
        else:
            amount = compProfile.package.annualPrice

        payfast_data = {

        }

        signature = ''
        # for key, value in payfast_data.items():
        #     signature += '{}={}&'.format(str(key), str(urllib.parse.urlencode(value)))

        signature = urlencode(payfast_data, quote_via=quote_plus)

        signature = hashlib.md5(signature.encode()).hexdigest()

        payfast_data.update({'signature': signature})

        payfastForm = PayFast_Form(payfast_data)

        context = {
            'invoice': invoice,
            'user': userObj,
            'comp_prof': compProfile,
            'ourDetails': ourDetails,
            'payfast_form': payfastForm,
            'signature': signature.strip()
        }

        return render(request, 'invoice.html', context)


@login_required
def profile_view(request):
    pass



def password_change_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/user_accounts/profile')
        else:
            return redirect('/user_accounts/password_change')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'pwd_change_form': form}
        return render(request, 'user_accounts/password_change.html', args)


#Password reset view
def password_reset_view(request):
    if request.method == 'POST':
        form = PasswordResetForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/user_accounts/profile')
        else:
            return redirect('/user_accounts/password_change')
    else:
        form = PasswordResetForm(user=request.user)
        args = {'pwd_change_form': form}
        return render(request, 'user_accounts/password_change.html', args)

#This is the function that handle the auto complete search functionality.
def autocomplete_search_view(request):
    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = ''
        return HttpResponse([{}], content_type='application/json')

    swList = search_text.split()

    keywords = []
    if len(swList) == 1:
        keywords = Keywords.objects.filter(keyword__icontains=swList[0].strip())
    else:
        keywords = Keywords.objects.filter(keyword__icontains=swList[0].strip()).filter(keyword__icontains=swList[1].strip())

    data = serializers.serialize('json', keywords, fields=('keyword'))
    return HttpResponse(data, content_type='application/json')


# this view handles the update of the Company Profile.
def UpdateCompanyProfile(request, pk):
    pass
    # compObj = get_object_or_404(CompanyProfile, pk=pk)

    # if request.user == compObj.user:
    #     if request.method == 'POST':
    #         companyProfileEditFormObj = CompanyProfileEditForm(data=request.POST, instance=compObj)
    #         if companyProfileEditFormObj.is_valid():
    #             editedCompObj = companyProfileEditFormObj.save()

    #             keyword_ids_str = companyProfileEditFormObj.cleaned_data['keywordListItem']

    #             if len(keyword_ids_str) > 0:
    #                 keyword_ids = keyword_ids_str.split(',')
    #                 editedCompObj.keywords.clear()
    #                 for keyword_id in keyword_ids:
    #                     keywordObj = Keywords.objects.get(id=int(keyword_id.strip()))

user_accounts/templates/authentication/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Login' only %}
{% endblock homepage_banner  %}

{% block content %}

        <div class="formcontainer container page">

                {% include 'form-errors.html' %}

                <form class="login-form" action="{% url 'user_accounts:auth' %}" method="post">{% csrf_token %}


                    {% if form.errors %}
                    <p class="error">Sorry, that's not a valid username and password</p>
                    {% endif %}
                    
                     

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <span class="input-group-text"><i class="lni-user"></i></span>                                  
                            </div>
                        </div>
                        <input class="form-control" type="email" placeholder="Email" name="email" value="" id="email" autocomplete="current-password">
                    </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <span class="input-group-text"><i class="fa fa-lock" aria-hidden="true"></i></span>                                  
                                </div>
                            </div>
                            <input class="form-control" type="password" placeholder="Password" name="password" value="" id="password" autocomplete="current-password">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="input-group-text"><i class="fa fa-eye-slash" id="togglePassword" onclick="hide_show_pwd(this)" style="cursor: pointer"></i></span>
                                </div>
                            </div>
                        </div>

                                     
                    
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}

                    <input type="submit" class="btn btn-secondary btn-sm" value="login" style="float: right;" />
                    <a href="{% url 'user_accounts:password_reset'%}">Forgot Password</a>


                    
                </form>
            

    </div>



{% endblock %}

user_accounts/templates/authentication/password_change.html
{% extends "base.html" %}
{% load static %}
{% block title %}Change Password{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Change Password' only %}
{% endblock homepage_banner  %}

{% block content %}
<div class="page_header">     
</div>

<div class="data_wrapper page p-3" style="min-height: 100vh;">
        <form role="form" method="post">
            {% csrf_token %}
            {{ pwd_change_form.as_p }}
            <button class="btn btn-success btn-lg pull-right" type="submit">Submit</button>
        </form>
    </div>


{% endblock %}

user_accounts/templates/authentication/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reset{% endblock %}
{% block content %}

{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

{% endblock %}

user_accounts/templates/authentication/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Passwords Reset Complete{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Password Reset Complete' only %}
{% endblock homepage_banner  %}

{% block content %}

<div class="page_header">     
</div>

<div class="data_wrapper page p-3" style="min-height: 100vh;">


<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

</div>

{% endblock %}

user_accounts/templates/authentication/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Password Reset Confirm{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Password Reset Confirm' only %}
{% endblock homepage_banner  %}

{% block content %}


{% if validlink %}


<div class="page_header">     
</div>

<div class="data_wrapper page p-3" style="min-height: 100vh;">
    <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
    <form method="post">{% csrf_token %}
        <fieldset class="module aligned">
            <div class="form-row field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">{% trans 'New password:' %}</label>
                {{ form.new_password1 }}
            </div>
            <div class="form-row field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
                {{ form.new_password2 }}
            </div>

            <input type="submit" value="{% trans 'Change my password' %}" />
        </fieldset>
    </form>
</div>


{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

user_accounts/templates/authentication/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Password Reset sent{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Password Reset Done' only %}
{% endblock homepage_banner  %}

{% block content %}
<div class="page_header">     
</div>

<div class="data_wrapper page p-3" style="min-height: 100vh;">
    <h3>Password Reset sent</h3>
<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

</div>

{% endblock %}

user_accounts/templates/authentication/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}Password Reset form{% endblock %}

{% block homepage_banner %}
{% include 'banner.html' with page='Password Reset Form' only %}
{% endblock homepage_banner  %}


{% block content %}


<div class="page_header">     
</div>

<div class="data_wrapper page p-3" style="min-height: 100vh;">

    <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

    <form method="post">{% csrf_token %}
        <fieldset class="module aligned">
            <div class="inline-form field-email">
                {{ form.email.errors }}

                    <label for="id_email">{% trans 'Email address:' %}</label>
                    {{ form.email }}

                    <input type="submit" value="{% trans 'Reset my password' %}" />
            </div>
        </fieldset>
    </form>
</div>


{% endblock %}