dashboard/urls.py
from django.urls import path
from . import views

app_name ='dashboard'

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('tender/<int:pk>/', views.TenderView.as_view(), name='tender'),
    path('tenders/', views.TendersView.as_view(), name='tenders'),
]

saleads/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'saleads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('user-accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('pricing-plans/', include('pricing_plans.urls', namespace='pricing_plans')),
    path('leads-and-tenders/', include('leads_and_tenders.urls', namespace='leads_and_tenders')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
    path('contact-us/', include('contact_us.urls', namespace='contact_us')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('service-provider/', include('service_provider.urls', namespace='service_provider')),
    path('invoices/', include('invoices.urls', namespace='invoices')),
]

dashboard/models.py
from django.db import models

dashboard/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.base import View, ContextMixin
from homepage.forms import TenderSearchForm
from leads_and_tenders.models import Tender, SP_Tender

class Dashboard(View, ContextMixin):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = TenderSearchForm()
        sp = SP_Tender.objects.filter(service_provider=self.request.user.service_provider)
        context['matched_tenders'] = sp
        return context
    
    def get(self, request, **kwargs):
        return render(request, self.template_name, self.get_context_data())


# displays all the current tenders.
class TendersView(View, ContextMixin):
    template_name = 'tenders/tenders.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def get(self, request, **kwargs):
        return render(request, self.template_name, self.get_context_data())
    
# displays a tender.
class TenderView(View, ContextMixin):
    template_name = 'tenders/tender.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tender'] = Tender.objects.get(pk=self.kwargs['pk'])
        return context
    
    def get(self, request, **kwargs):
        return render(request, self.template_name, self.get_context_data())

dashboard/templates/tenders/tender.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block title %}Tender{% endblock title %}

{% block dashboard %}
<div class="page-content">
    <div class="row">
      <div class="col-12 col-xl-12 stretch-card">
        <div class="card overflow-hidden content-container">
          <div class="card-body tendercontainer">
            <div class="d-flex justify-content-between align-items-baseline mb-4 mb-md-3">
              <h6 class="card-title mb-0">{{tender.summary}}</h6>
              <div class="dropdown">
                <a type="button" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="eye"
                      class="icon-sm me-2"></i> <span class="">View</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="edit-2"
                      class="icon-sm me-2"></i> <span class="">Edit</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="trash"
                      class="icon-sm me-2"></i> <span class="">Delete</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="printer"
                      class="icon-sm me-2"></i> <span class="">Print</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="download"
                      class="icon-sm me-2"></i> <span class="">Download</span></a>
                </div>
              </div>
            </div>

            {{tender.description|safe}}
                      
            <!-- <table class="table table-sm table-responsive">
                <tr>
                    <td>Ref Number</td>
                    <td>{{tender.refNum}}</td>
                </tr>
                <tr>
                    <td>Date Published</td>
                    <td>{% if tender.datePublished == None %}N/A{% else %}{{tender.datePublished}}{% endif %}</td>
                </tr>
                <tr>
                    <td>Closing Date</td>
                    <td><span class="text-danger">{{tender.closingDate}}</span></td>
                </tr>
                <tr>
                    <td>Site Inspection Date</td>
                    <td><span class="text-success">{% if tender.siteInspectionDate == None %}N/A{% else %}{{tender.siteInspectionDate}}{% endif %}</span></td>
                </tr>
                <tr>
                    <td>Site Inspection Address</td>
                    <td>{% if tender.siteInspectionAddress == None %}N/A{% else %}{{tender.siteInspectionAddress}}{% endif %}</td>
                </tr>
                <tr>
                    <td>Ref Number</td>
                    <td>{% if tender.enquiries == None %}N/A{% else %}{{tender.enquiries}}{% endif %}</td>

                </tr>
                <tr>
                    <td>Ref Number</td>
                    <td>{% if tender.description == None %}N/A{% else %}{{tender.description|safe}}{% endif %}</td>
                </tr>
                <tr>
                    <td>Ref Number</td>
                    <td>{{tender.refNum}}</td>
                </tr>
                <tr>
                    <td>Ref Number</td>
                    <td>{{tender.refNum}}</td>
                </tr>
                <tr>
                    <td>Ref Number</td>
                    <td>{{tender.refNum}}</td>
                </tr>
            </table> -->


          </div>
        </div>
      </div>
    </div> <!-- row -->
  
  
  </div>
{% endblock dashboard %}

dashboard/templates/tenders/tenders.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block title %}Tenders{% endblock title %}

{% block dashboard %}
<div class="page-content">
    <div class="row">
      <div class="col-12 col-xl-12 grid-margin stretch-card">
        <div class="card overflow-hidden content-container">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-baseline mb-4 mb-md-3">
              <h6 class="card-title mb-0">Current Tenders</h6>
              <div class="dropdown">
                <a type="button" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  <i class="icon-lg text-muted pb-3px" data-feather="more-horizontal"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="eye"
                      class="icon-sm me-2"></i> <span class="">View</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="edit-2"
                      class="icon-sm me-2"></i> <span class="">Edit</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="trash"
                      class="icon-sm me-2"></i> <span class="">Delete</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="printer"
                      class="icon-sm me-2"></i> <span class="">Print</span></a>
                  <a class="dropdown-item d-flex align-items-center" href="javascript:;"><i data-feather="download"
                      class="icon-sm me-2"></i> <span class="">Download</span></a>
                </div>
              </div>
            </div>
                      
            <section id="tenderscontainer">
              
              <form class="mb-3">
                <div class="row">
                  <div class="col-sm-4">
                    {{search_form.searchField}}
                  </div>
                  <div class="col-sm-3">
                    {{search_form.categorySelectionField}}
                  </div>
                  <div class="col-sm-3">
                    {{search_form.provinceSelectionField}}
                  </div>
                  <div class="col-sm-2">
                    <input type="submit" class="btn btn-outline-secondary search_btn" value="Search">
                  </div>
                </div>
              </form>
  
               <table class="tenders-table table_">
                <thead>
                  <tr class="text-secondary" style="text-transform: uppercase;">
                    <th class="fcol" scope="col" style="width: 15%;">Ref</th>
                    <th scope="col" style="width: 55%;">Description</th>
                    <th class="scol" scope="col" style="width: 15%;">Site Inspection</th>
                    <th scope="col" style="width: 15%;">Closing Date</th>
                  </tr>
                </thead>
                <tbody>
                  {% for tender in page_obj %}
                  <tr style="font-size: .8em;">
                    <th class="text-secondary fcol" scope="row">{{tender.refNum|truncatechars:11}}</th>
                    <td>
                      <a href="{% url 'dashboard:tender' pk=tender.pk %}">{{tender.summary|upper|truncatechars:350}}</a>
                    </td>
                    <td class="scol">
                      {% if tender.siteInspectionDate is None %}
                        N/A
                      {% else %}
                        {{tender.siteInspectionDate}}
                      {% endif %}
                    </td>
                    <td>{{tender.closingDate}}</td>
                  </tr>
                  {% empty %}
                      <span class="text-danger">No available tenders yet.</span>
                  {% endfor %}
                </tbody>
              </table>
              {% include 'paginator.html' %}
            </section>
          </div>
        </div>
      </div>
    </div> <!-- row -->
  
  
  </div>
{% endblock dashboard %}