homepage/urls.py
from django.urls import path, re_path
from .views import (
    Home,
)

app_name = "homepage"

urlpatterns = [
    path('', Home.as_view(), name='homepage'),
]

saleads/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'saleads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('user-accounts/', include('user_accounts.urls', namespace='user_accounts')),
    path('pricing-plans/', include('pricing_plans.urls', namespace='pricing_plans')),
    path('leads-and-tenders/', include('leads_and_tenders.urls', namespace='leads_and_tenders')),
    path('about-us/', include('about_us.urls', namespace='about_us')),
    path('contact-us/', include('contact_us.urls', namespace='contact_us')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('companies/', include('companies.urls', namespace='companies')),
    path('service-provider/', include('service_provider.urls', namespace='service_provider')),
    path('invoices/', include('invoices.urls', namespace='invoices')),
]

saleads/templates/banner.html
{% load static %}
<div class="page-header" style="background: url({% static 'img/banner1.jpg' %});">
    <div class="container">
    <div class="row">
    <div class="col-md-12">
    <div class="breadcrumb-wrapper">
    <h2 class="product-title">{{page}}</h2>
    <ol class="breadcrumb">
    <li><a href="{% url 'homepage:homepage' %}">Home /</a></li>
    <li class="current">{{page}}</li>
    </ol>
    </div>
    </div>
    </div>
    </div>
    </div>

saleads/templates/form-errors.html
{% load static %}

{% if messages %}
    <div class="col-xs-12">
        {% for message in messages %}
            {% if message.level == 30 %}
                <div class="alert alert-danger" role="alert" style="text-align: center;">
                    {{message}}
                </div>
            {% else %}
                <div class="alert alert-success" role="alert" style="text-align: center;">
                    {{message}}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

saleads/templates/paginator.html
{% load static %}


    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="homepage_link">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="homepage_link">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="homepage_link">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="homepage_link">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    